import {
  buildWorkspaceAgentContextCliArgs,
  buildWorkspaceAgentSyncCliArgs,
} from './agentContextPack';
import { DASHBOARD_WORKSPACE_COMMAND_SOURCE } from './workspaceCommandPresets';
import { resolveDashboardCommandSurface } from '../contracts/dashboardCommandSurface';

export type DashboardCommandScope = 'workspace' | 'project' | 'module' | 'system';

export type DashboardCommandExecutionMode =
  | 'webview-local'
  | 'extension-host-handler'
  | 'vscode-command'
  | 'terminal-rapidkit'
  | 'terminal-shell';

export type DashboardCommandPayloadKind =
  | 'none'
  | 'workspace'
  | 'project-path'
  | 'project-context'
  | 'module-maintenance';

export type DashboardCommandContract = {
  id: string;
  label: string;
  scope: DashboardCommandScope;
  executionMode: DashboardCommandExecutionMode;
  trackActivity: boolean;
  requiresWorkspace?: boolean;
  requiresProject?: boolean;
  cliArgs?: string[];
  vscodeCommand?: string;
  payloadKind?: DashboardCommandPayloadKind;
  payloadDefaults?: Record<string, unknown>;
};

export const DASHBOARD_COMMAND_CONTRACTS = {
  openSetup: {
    id: 'openSetup',
    label: 'Open Setup',
    scope: 'system',
    executionMode: 'webview-local',
    trackActivity: false,
  },
  openCreateWorkspace: {
    id: 'openCreateWorkspace',
    label: 'Create Workspace',
    scope: 'system',
    executionMode: 'webview-local',
    trackActivity: false,
  },
  refreshModules: {
    id: 'refreshModules',
    label: 'Refresh Modules',
    scope: 'system',
    executionMode: 'extension-host-handler',
    trackActivity: false,
  },
  importWorkspace: {
    id: 'importWorkspace',
    label: 'Import Workspace',
    scope: 'system',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.importWorkspace',
  },
  importProject: {
    id: 'importProject',
    label: 'Import Project',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    cliArgs: ['import'],
    vscodeCommand: 'workspai.importProject',
  },
  adoptProject: {
    id: 'adoptProject',
    label: 'Adopt Project',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    cliArgs: ['adopt'],
    vscodeCommand: 'workspai.adoptProject',
  },
  quickSwitchWorkspace: {
    id: 'quickSwitchWorkspace',
    label: 'Switch Workspace',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    vscodeCommand: 'workspai.quickSwitchWorkspace',
  },
  checkWorkspaceHealth: {
    id: 'checkWorkspaceHealth',
    label: 'Workspace Doctor',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['doctor', 'workspace'],
    vscodeCommand: 'workspai.checkWorkspaceHealth',
  },
  exportWorkspace: {
    id: 'exportWorkspace',
    label: 'Export Workspace',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.exportWorkspace',
  },
  workspaceBootstrap: {
    id: 'workspaceBootstrap',
    label: 'Workspace Bootstrap',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['bootstrap', '--ci'],
    vscodeCommand: 'workspai.workspaceBootstrap',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceSetup: {
    id: 'workspaceSetup',
    label: 'Setup',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['setup'],
    vscodeCommand: 'workspai.workspaceSetup',
  },
  workspaceSync: {
    id: 'workspaceSync',
    label: 'Workspace Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'sync'],
    vscodeCommand: 'workspai.workspaceSync',
  },
  workspaceFoundationEnsure: {
    id: 'workspaceFoundationEnsure',
    label: 'Foundation Ensure',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'foundation', 'ensure', '--json'],
    vscodeCommand: 'workspai.workspaceFoundationEnsure',
    payloadDefaults: { mode: 'ensure', json: true },
  },
  workspaceContractInspect: {
    id: 'workspaceContractInspect',
    label: 'Contract Inspect',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'inspect', '--json'],
    vscodeCommand: 'workspai.workspaceContractInspect',
  },
  workspaceContractVerify: {
    id: 'workspaceContractVerify',
    label: 'Contract Verify',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'verify', '--strict', '--json'],
    vscodeCommand: 'workspai.workspaceContractVerify',
  },
  workspaceContractInit: {
    id: 'workspaceContractInit',
    label: 'Contract Init',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'init'],
    vscodeCommand: 'workspai.workspaceContractInit',
  },
  workspaceContractSync: {
    id: 'workspaceContractSync',
    label: 'Contract Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'sync', '--strict', '--json'],
    vscodeCommand: 'workspai.workspaceContractSync',
  },
  workspaceContractGraph: {
    id: 'workspaceContractGraph',
    label: 'Workspace Graph',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'contract', 'graph', '--json'],
    vscodeCommand: 'workspai.workspaceContractGraph',
  },
  workspaceContract: {
    id: 'workspaceContract',
    label: 'Workspace Contract',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceContract',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceContractOpen: {
    id: 'workspaceContractOpen',
    label: 'Open Workspace Contract',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceContractOpen',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceRunTest: {
    id: 'workspaceRunTest',
    label: 'Workspace Test',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'test'],
    vscodeCommand: 'workspai.workspaceRunTest',
  },
  workspaceRunInit: {
    id: 'workspaceRunInit',
    label: 'Workspace Init',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'init'],
    vscodeCommand: 'workspai.workspaceRunInit',
  },
  workspaceRunBuild: {
    id: 'workspaceRunBuild',
    label: 'Workspace Build',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'build'],
    vscodeCommand: 'workspai.workspaceRunBuild',
  },
  workspaceRunStart: {
    id: 'workspaceRunStart',
    label: 'Workspace Start',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'start'],
    vscodeCommand: 'workspai.workspaceRunStart',
  },
  workspaceRunStage: {
    id: 'workspaceRunStage',
    label: 'Workspace Run Stage',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', '<stage>'],
    vscodeCommand: 'workspai.workspaceRunStage',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceInit: {
    id: 'workspaceInit',
    label: 'Workspace Init',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'run', 'init'],
    vscodeCommand: 'workspai.workspaceInit',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceTerminal: {
    id: 'workspaceTerminal',
    label: 'Workspace Terminal',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceTerminal',
  },
  workspaceAnalyze: {
    id: 'workspaceAnalyze',
    label: 'Workspace Analyze',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['analyze', '--json'],
    vscodeCommand: 'workspai.workspaceAnalyze',
  },
  workspaceReadiness: {
    id: 'workspaceReadiness',
    label: 'Release Readiness',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['readiness'],
    vscodeCommand: 'workspai.workspaceReadiness',
  },
  workspacePipeline: {
    id: 'workspacePipeline',
    label: 'Governance Gate',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['pipeline', '--json', '--strict'],
    vscodeCommand: 'workspai.workspacePipeline',
  },
  workspaceModel: {
    id: 'workspaceModel',
    label: 'Workspace Model',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'model', '--json', '--write'],
    vscodeCommand: 'workspai.workspaceModel',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceEvaluationReport: {
    id: 'workspaceEvaluationReport',
    label: 'Finalize Agent Evaluation',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'eval', 'report', '--json'],
    vscodeCommand: 'workspai.workspaceEvaluationReport',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceEvaluationStatus: {
    id: 'workspaceEvaluationStatus',
    label: 'Agent Evaluation Status',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'eval', 'status', '--json'],
    vscodeCommand: 'workspai.workspaceEvaluationStatus',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGraphSearch: {
    id: 'workspaceGraphSearch',
    label: 'Search Workspace Graph',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'graph', 'search'],
    vscodeCommand: 'workspai.workspaceGraphSearch',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGraphBenchmarkSuite: {
    id: 'workspaceGraphBenchmarkSuite',
    label: 'Generate Agent Retrieval Benchmark',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: [
      'workspace',
      'graph',
      'benchmark-suite',
      'agent-core.v1',
      '--limit',
      '20',
      '--write',
      '--json',
    ],
    vscodeCommand: 'workspai.workspaceGraphBenchmarkSuite',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGraphExportJsonLd: {
    id: 'workspaceGraphExportJsonLd',
    label: 'Export Workspace Graph as JSON-LD',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'graph', 'jsonld', '--json'],
    vscodeCommand: 'workspai.workspaceGraphExport.jsonld',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGraphExportGraphMl: {
    id: 'workspaceGraphExportGraphMl',
    label: 'Export Workspace Graph as GraphML',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'graph', 'graphml', '--json'],
    vscodeCommand: 'workspai.workspaceGraphExport.graphml',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGraphExportGexf: {
    id: 'workspaceGraphExportGexf',
    label: 'Export Workspace Graph as GEXF',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'graph', 'gexf', '--json'],
    vscodeCommand: 'workspai.workspaceGraphExport.gexf',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceIntelligenceSnapshot: {
    id: 'workspaceIntelligenceSnapshot',
    label: 'Intelligence Snapshot',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'snapshot', '--json'],
    vscodeCommand: 'workspai.workspaceIntelligenceSnapshot',
  },
  workspaceDiff: {
    id: 'workspaceDiff',
    label: 'Workspace Diff',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'diff', '--json'],
    vscodeCommand: 'workspai.workspaceDiff',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceImpact: {
    id: 'workspaceImpact',
    label: 'Workspace Impact',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'impact', '--json'],
    vscodeCommand: 'workspai.workspaceImpact',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceVerify: {
    id: 'workspaceVerify',
    label: 'Workspace Verify',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'verify', '--json'],
    vscodeCommand: 'workspai.workspaceVerify',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceExplain: {
    id: 'workspaceExplain',
    label: 'Workspace Explain',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'explain', 'release-blocked', '--json', '--write'],
    vscodeCommand: 'workspai.workspaceExplain',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceWhy: {
    id: 'workspaceWhy',
    label: 'Workspace Why',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'why', 'release-blocked', '--json', '--write'],
    vscodeCommand: 'workspai.workspaceWhy',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceTrace: {
    id: 'workspaceTrace',
    label: 'Workspace Trace',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: [
      'workspace',
      'trace',
      '--from',
      '.workspai/reports/workspace-model-diff-last-run.json',
      '--json',
      '--write',
    ],
    vscodeCommand: 'workspai.workspaceTrace',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceRemediationPlan: {
    id: 'workspaceRemediationPlan',
    label: 'Workspace Repair Plan',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'remediation-plan', '--ci', '--json', '--write', '--include-paths'],
    vscodeCommand: 'workspai.workspaceRemediationPlan',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceWatch: {
    id: 'workspaceWatch',
    label: 'Workspace Watch',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'watch', '--once', '--json'],
    vscodeCommand: 'workspai.workspaceWatch',
  },
  live: {
    id: 'live',
    label: 'Live Activity',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['live'],
    vscodeCommand: 'workspai.live',
  },
  workspaceMcp: {
    id: 'workspaceMcp',
    label: 'Workspace MCP Serve',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'mcp', 'serve'],
    vscodeCommand: 'workspai.workspaceMcp',
  },
  workspaceImpactLens: {
    id: 'workspaceImpactLens',
    label: 'Workspace Advisor',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'workspace',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'workspace_intelligence',
    },
  },
  workspaceImpactLensCli: {
    id: 'workspaceImpactLensCli',
    label: 'Impact Lens',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceImpactLens',
    payloadKind: 'workspace',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'workspace_intelligence',
    },
  },
  workspaceContextAgent: {
    id: 'workspaceContextAgent',
    label: 'Agent Context Pack',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: buildWorkspaceAgentContextCliArgs(),
    vscodeCommand: 'workspai.workspaceContextAgent',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceAgentSync: {
    id: 'workspaceAgentSync',
    label: 'Agent Grounding Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: buildWorkspaceAgentSyncCliArgs(),
    vscodeCommand: 'workspai.workspaceAgentSync',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceIntelligenceChain: {
    id: 'workspaceIntelligenceChain',
    label: 'Intelligence Chain',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceIntelligenceChain',
  },
  workspaceGoalCreate: {
    id: 'workspaceGoalCreate',
    label: 'Create Governed Goal',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceGoalCreate',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceGoalShow: {
    id: 'workspaceGoalShow',
    label: 'Review Governed Goals',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.workspaceGoalShow',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceAutopilotRelease: {
    id: 'workspaceAutopilotRelease',
    label: 'Autopilot Release',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['autopilot', 'release'],
    vscodeCommand: 'workspai.workspaceAutopilotRelease',
  },
  workspaceShare: {
    id: 'workspaceShare',
    label: 'Share Bundle',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'share'],
    vscodeCommand: 'workspai.exportWorkspaceShareBundle',
  },
  workspaceSnapshotCreate: {
    id: 'workspaceSnapshotCreate',
    label: 'Recovery Snapshot',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot', 'create'],
    vscodeCommand: 'workspai.workspaceSnapshotCreate',
  },
  workspaceSnapshot: {
    id: 'workspaceSnapshot',
    label: 'Recovery Snapshot Tools',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot'],
    vscodeCommand: 'workspai.workspaceSnapshot',
  },
  workspaceSnapshotList: {
    id: 'workspaceSnapshotList',
    label: 'List Snapshots',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot', 'list'],
    vscodeCommand: 'workspai.workspaceSnapshotList',
  },
  workspaceSnapshotInspect: {
    id: 'workspaceSnapshotInspect',
    label: 'Inspect Snapshot',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot', 'inspect'],
    vscodeCommand: 'workspai.workspaceSnapshotInspect',
  },
  workspaceSnapshotRestore: {
    id: 'workspaceSnapshotRestore',
    label: 'Restore Snapshot',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['snapshot', 'restore'],
    vscodeCommand: 'workspai.workspaceSnapshotRestore',
  },
  workspacePolicyShow: {
    id: 'workspacePolicyShow',
    label: 'Policy Review',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'policy', 'show'],
    vscodeCommand: 'workspai.workspacePolicyShow',
  },
  workspacePolicySet: {
    id: 'workspacePolicySet',
    label: 'Policy Update',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'policy', 'set', '<key>', '<value>'],
    vscodeCommand: 'workspai.workspacePolicySet',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  cacheClear: {
    id: 'cacheClear',
    label: 'Cache Clear',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['cache', 'clear'],
    vscodeCommand: 'workspai.cacheClear',
  },
  cachePrune: {
    id: 'cachePrune',
    label: 'Cache Prune',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['cache', 'prune'],
    vscodeCommand: 'workspai.cachePrune',
  },
  cacheRepair: {
    id: 'cacheRepair',
    label: 'Cache Repair',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['cache', 'repair'],
    vscodeCommand: 'workspai.cacheRepair',
  },
  mirrorSync: {
    id: 'mirrorSync',
    label: 'Mirror Sync',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'sync'],
    vscodeCommand: 'workspai.mirrorSync',
  },
  mirrorOps: {
    id: 'mirrorOps',
    label: 'Mirror Operations',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.mirrorOps',
  },
  mirrorStatus: {
    id: 'mirrorStatus',
    label: 'Mirror Status',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'status'],
    vscodeCommand: 'workspai.mirrorStatus',
  },
  mirrorVerify: {
    id: 'mirrorVerify',
    label: 'Mirror Verify',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'verify'],
    vscodeCommand: 'workspai.mirrorVerify',
  },
  mirrorRotate: {
    id: 'mirrorRotate',
    label: 'Mirror Rotate',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['mirror', 'rotate'],
    vscodeCommand: 'workspai.mirrorRotate',
  },
  cacheStatus: {
    id: 'cacheStatus',
    label: 'Cache Status',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['cache', 'status'],
    vscodeCommand: 'workspai.cacheStatus',
  },
  workspaceInfra: {
    id: 'workspaceInfra',
    label: 'Infra Plan',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'plan'],
    vscodeCommand: 'workspai.infra',
  },
  infraPlan: {
    id: 'infraPlan',
    label: 'Infra Plan',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'plan'],
    vscodeCommand: 'workspai.infraPlan',
  },
  infraUp: {
    id: 'infraUp',
    label: 'Infra Up',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'up'],
    vscodeCommand: 'workspai.infraUp',
  },
  infraDown: {
    id: 'infraDown',
    label: 'Infra Down',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'down'],
    vscodeCommand: 'workspai.infraDown',
  },
  infraStatus: {
    id: 'infraStatus',
    label: 'Infra Status',
    scope: 'workspace',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['infra', 'status'],
    vscodeCommand: 'workspai.infraStatus',
  },
  infraOpenCompose: {
    id: 'infraOpenCompose',
    label: 'Infra Open Compose',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    vscodeCommand: 'workspai.infraOpenCompose',
    payloadKind: 'workspace',
    payloadDefaults: { source: DASHBOARD_WORKSPACE_COMMAND_SOURCE },
  },
  workspaceArchive: {
    id: 'workspaceArchive',
    label: 'Archive Tools',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'archive'],
    vscodeCommand: 'workspai.workspaceArchive',
  },
  workspaceArchiveVerify: {
    id: 'workspaceArchiveVerify',
    label: 'Verify Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'archive', 'verify'],
    vscodeCommand: 'workspai.workspaceArchiveVerify',
  },
  workspaceArchiveInspect: {
    id: 'workspaceArchiveInspect',
    label: 'Inspect Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'archive', 'inspect'],
    vscodeCommand: 'workspai.workspaceArchiveInspect',
  },
  workspaceArchiveDoctor: {
    id: 'workspaceArchiveDoctor',
    label: 'Doctor Archive',
    scope: 'workspace',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresWorkspace: true,
    cliArgs: ['workspace', 'archive', 'doctor'],
    vscodeCommand: 'workspai.workspaceArchiveDoctor',
  },
  projectTerminal: {
    id: 'projectTerminal',
    label: 'Project Terminal',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectTerminal',
  },
  projectInit: {
    id: 'projectInit',
    label: 'Project Init',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['init'],
    vscodeCommand: 'workspai.projectInit',
  },
  projectDev: {
    id: 'projectDev',
    label: 'Project Dev',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['dev'],
    vscodeCommand: 'workspai.projectDev',
  },
  projectStop: {
    id: 'projectStop',
    label: 'Project Stop',
    scope: 'project',
    executionMode: 'terminal-shell',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectStop',
  },
  projectTest: {
    id: 'projectTest',
    label: 'Project Test',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['test'],
    vscodeCommand: 'workspai.projectTest',
  },
  projectDoctor: {
    id: 'projectDoctor',
    label: 'Project Doctor',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['doctor', 'project'],
    vscodeCommand: 'workspai.projectDoctor',
    payloadKind: 'project-path',
    payloadDefaults: {
      preferredAction: 'check',
    },
  },
  projectArchitecture: {
    id: 'projectArchitecture',
    label: 'Architecture Map',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openArchitectureMap',
    payloadKind: 'project-context',
  },
  projectIncident: {
    id: 'projectIncident',
    label: 'Studio',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openIncidentStudio',
    payloadKind: 'project-context',
  },
  projectAI: {
    id: 'projectAI',
    label: 'Workspace Advisor',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectRelease: {
    id: 'projectRelease',
    label: 'Release Commander',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.aiReleaseReadinessCommander',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectImpact: {
    id: 'projectImpact',
    label: 'Workspace Advisor',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.openWorkspaceAdvisor',
    payloadKind: 'project-context',
    payloadDefaults: {
      source: 'dashboard',
      trigger: 'project_actions',
    },
  },
  projectBrowser: {
    id: 'projectBrowser',
    label: 'Project Browser',
    scope: 'project',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    vscodeCommand: 'workspai.projectBrowser',
  },
  projectBuild: {
    id: 'projectBuild',
    label: 'Project Build',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['build'],
    vscodeCommand: 'workspai.projectBuild',
  },
  projectLint: {
    id: 'projectLint',
    label: 'Project Lint',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['lint'],
    vscodeCommand: 'workspai.projectLint',
  },
  projectFormat: {
    id: 'projectFormat',
    label: 'Project Format',
    scope: 'project',
    executionMode: 'terminal-rapidkit',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['format'],
    vscodeCommand: 'workspai.projectFormat',
  },
  moduleDiff: {
    id: 'moduleDiff',
    label: 'Module Diff',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['diff', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleDiff',
  },
  moduleRollback: {
    id: 'moduleRollback',
    label: 'Module Rollback',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['rollback', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleRollback',
  },
  moduleUninstall: {
    id: 'moduleUninstall',
    label: 'Module Uninstall',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['uninstall', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleUninstall',
  },
  moduleUpgrade: {
    id: 'moduleUpgrade',
    label: 'Module Upgrade',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['upgrade', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleUpgrade',
  },
  moduleCheckpoint: {
    id: 'moduleCheckpoint',
    label: 'Module Checkpoint',
    scope: 'module',
    executionMode: 'vscode-command',
    trackActivity: true,
    requiresProject: true,
    cliArgs: ['checkpoint', 'module', '<slug>'],
    vscodeCommand: 'workspai.moduleCheckpoint',
  },
} as const satisfies Record<string, DashboardCommandContract>;

export type DashboardCommandId = keyof typeof DASHBOARD_COMMAND_CONTRACTS;

export function resolveDashboardCommandContract(
  command: string
): DashboardCommandContract | undefined {
  return DASHBOARD_COMMAND_CONTRACTS[command as DashboardCommandId];
}

export function resolveDashboardCommandContractByVscodeCommand(
  vscodeCommand: string
): DashboardCommandContract | undefined {
  return (Object.values(DASHBOARD_COMMAND_CONTRACTS) as DashboardCommandContract[]).find(
    (contract) => contract.vscodeCommand === vscodeCommand
  );
}

export function getDashboardCommandActivity(command: string): {
  label: string;
  scope: DashboardCommandScope;
} {
  const surface = resolveDashboardCommandSurface(command);
  if (surface) {
    return { label: surface.label, scope: surface.scope };
  }

  const contract = resolveDashboardCommandContract(command);
  if (contract) {
    return { label: contract.label, scope: contract.scope };
  }
  return {
    label: command.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
    scope: 'system',
  };
}
